"""extra fields in product

Revision ID: 82e319d68579
Revises: 82a5e4ce2c36
Create Date: 2025-09-29 18:25:39.852002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e319d68579'
down_revision = '82a5e4ce2c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('warranty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('warranty')
        batch_op.drop_column('features')
        batch_op.drop_column('specs')
        batch_op.drop_column('category')
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
