"""Fix portfolio_id typo and add FAQ relationship

Revision ID: d2812d97da11
Revises: 82e319d68579
Create Date: 2025-10-27 22:13:15.878797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2812d97da11'
down_revision = '82e319d68579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'portfolio', ['portfolio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###
