"""Fix FAQ 

Revision ID: e1360972c9f8
Revises: d2812d97da11
Create Date: 2025-10-27 22:24:54.971312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1360972c9f8'
down_revision = 'd2812d97da11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name='faq_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='faq_pkey')
    )
    # ### end Alembic commands ###
